import { Inter, Kablammo, MedievalSharp, Libre_Barcode_128_Text} from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar"

const inter = Inter({ subsets: ["latin"] });

const medeivalSharp = MedievalSharp({weight: "400", subsets: ["latin"]})

export const kablammo = Kablammo({weight: "variable", subsets: ["latin"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barcode = Libre_Barcode_128_Text({
  weight: "400",
  subsets: ["latin"],
  variable: '--barcode' 
})

export default function RootLayout({ children }) {
  console.log(medeivalSharp)
  return (
    <html lang="en">
      <body className={`${inter.className} ${barcode.variable}`}>
        <NavBar />
        {children}
        </body>
    </html>
  );
}
