import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Link href='/posts'>Posts</Link>
          <Link href='/'>Home</Link>
        </header>
        {children}
        <footer>
          <p>Footer</p>
        </footer>
        </body>
    </html>
  );
}
